### ISSUE TITLE
Clicking on "+" brings back the last macro performed in the viewport

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#12]
When the Macro Editor is empty, adding a new macro brings back the previous macro that has been executed in the viewport.

1. Select an object in the viewport
2. Click on the "Record" button 
3. Move the object in the viewport
4. Click on the "Stop" button
5. Delete the object in the viewport 
6. Delete the "Move" macro in the Macro Editor (or Clear the Macro Editor)
7. Click on the "+" button

At this moment, you should notice that the newly created macro is named "Delete"

![ghjghg](https://user-images.githubusercontent.com/1732773/101597310-d7c9d980-39f6-11eb-80a5-6c50e50c4d6d.gif)

**Comment by InamuraJIN** [comment]
That's normal behavior.

It records the Action of deleting an object in the 3D viewport.
Also, operations in the macro editor are not recorded.

**Comment by xan2622** [comment]
It shouldn't record the "Deletion" of the cube.

As you notice in the GIF, I only recorded the "Movement" of the cube. 
I pressed PLAY, I moved the cube, then I pressed STOP.
I deleted the cube after I stopped recording.

**Comment by InamuraJIN** [comment]
I'm sorry.
I don't know what you want to do in the end.
If you want to keep track of "moves," you shouldn't delete the macro.
If you delete the object and then add the Macro, it will add the "Object Delete" macro

**Comment by xan2622** [comment]
I don't necessary want to record the "Move" operator (it was just an example, it could be any command).

What I tried to explain is that _Action Recorder_ creates a new macro named "Delete" when you press the + button.
And it should not. 

When the _Macro Editor_ is empty, pressing "+" should create a Empty macro, for example named "Action Recorder Empty macro" or "Empty" or "Double Click This Macro to add the Operator", not "Delete".

What I mean is that Action Recorder shouldn't even record the "Delete" operator since I haven't recorded it between "START" and "STOP".

**Comment by InamuraJIN** [comment]
Sorry.
"Record" isn't very accurate.
It has quite a few quirks.
E.g.
As Xan said, when you use the Operator, multiple Macro get recorded.
Unintended macros, such as vertex selection, may also be recorded.

It is not possible for me to define which Macro to record automatically and which Macro to ignore.
If the API changes, it could be very version dependent.
The "+Button" is necessary for manual recording

However, the problem of multiple Macros being registered in AutoRecord will be resolved eventually.
Right now, I don't know of a workaround yet

**Comment by RivinHD** [comment]
@xan2622 If you want to add an Empty Macro only use the "Add Event"-Button and select Empty to create one.
 The "Add Macro"-Button create a Macro from the last performed operation

**Comment by xan2622** [comment]
I think you haven't understood the issue that I reported. 

This bug report is about the "+" button that sometimes add an "Empty" macro (which is good, this is the expected behaviour), but sometimes, clicking on "+" adds the last operator that was executed in the viewport, just before clicking on "+". 

This is the bug I wanted to explain with the two GIFs. Clicking on "+" should only add an "Empty" macro, nothing else (not "Move", not "Delete", or else...).

The bug is still there in the add-on version 3.5.6

**Comment by InamuraJIN** [comment]
This "+ button" feature is not a bug, it's working correctly.
This will never be altered.
https://youtu.be/FqXxuMHuktc?t=13
Take a look at this video
It uses the "+" to add a Macro

https://github.com/InamuraJIN/ActionRecorder/issues/16#issuecomment-750472008
I was able to fix this problem.

However, it is impossible to solve problems like this
> Unintended macros, such as vertex selection, may also be recorded.
The reason is that the definition of the Macro needed by each user is ambiguous.
Some users need selection macros, some don't.
You can't define this in AutoRecord.

The "+Button" is there for users to define their own macros.
Since most of the viewport operations are described in InfoWIndow, you can record them in ActRec with "+".

Sometimes, a macro is created with "Empty" when the Info contains a string (other than bpy.ops~~) that ActRec can't get, or when there is no information.
Or, if the string can be retrieved but is marked with "Empty", that's a bug
