### ISSUE TITLE
Macro import

### ISSUE THREAD

**Issue by Egminator** [InamuraJIN/ActionRecorder#50]
Nice to see new versions of this addon absulutely love it for me its the one the best usefull addon for  blender but unfortunately ı cant import  my macros from 3.5.6 version to 4.0.7 I'm using blender 3.3.3

**Comment by RivinHD** [comment]
It should be possible to import the macros from an old version to the new version. This could be a bug.
Can you submit the macros you are trying to import?

**Comment by RivinHD** [comment]
Ok, I could successfully import your given macros into 4.0.7 of Action Recorder.
Here are the [macros](https://github.com/InamuraJIN/ActionRecorder/files/11162127/Macros.txt). You need to rename the file from `Macros.txt` to `Macros.json` before importing. (It's only .txt file because GitHub does not allow an upload of a .json file, the content is the same)


What OS do you use?

**Comment by Egminator** [comment]
Windows thank you for your fast response

**Comment by RivinHD** [comment]
Ok, that's weird, maybe it was just an issue in Blender 3.3
